
package com.iamszabo.jaxws.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarEndpointImplService", targetNamespace = "http://rpc.jaxws.iamszabo.com/", wsdlLocation = "http://localhost:9999/car?wsdl")
public class CarEndpointImplService
    extends Service
{

    private final static URL CARENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARENDPOINTIMPLSERVICE_EXCEPTION;
    private final static QName CARENDPOINTIMPLSERVICE_QNAME = new QName("http://rpc.jaxws.iamszabo.com/", "CarEndpointImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/car?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
        CARENDPOINTIMPLSERVICE_EXCEPTION = e;
    }

    public CarEndpointImplService() {
        super(__getWsdlLocation(), CARENDPOINTIMPLSERVICE_QNAME);
    }

    public CarEndpointImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARENDPOINTIMPLSERVICE_QNAME, features);
    }

    public CarEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, CARENDPOINTIMPLSERVICE_QNAME);
    }

    public CarEndpointImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARENDPOINTIMPLSERVICE_QNAME, features);
    }

    public CarEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarEndpoint
     */
    @WebEndpoint(name = "CarEndpointImplPort")
    public CarEndpoint getCarEndpointImplPort() {
        return super.getPort(new QName("http://rpc.jaxws.iamszabo.com/", "CarEndpointImplPort"), CarEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarEndpoint
     */
    @WebEndpoint(name = "CarEndpointImplPort")
    public CarEndpoint getCarEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rpc.jaxws.iamszabo.com/", "CarEndpointImplPort"), CarEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARENDPOINTIMPLSERVICE_EXCEPTION!= null) {
            throw CARENDPOINTIMPLSERVICE_EXCEPTION;
        }
        return CARENDPOINTIMPLSERVICE_WSDL_LOCATION;
    }

}
